In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
training_data = pd.read_csv("/kaggle/input/taxi-fare-guru-total-amount-prediction-challenge/train.csv")
training_data.head()
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/taxi-fare-guru-total-amount-prediction-challenge/sample.csv.csv
/kaggle/input/taxi-fare-guru-total-amount-prediction-challenge/train.csv
/kaggle/input/taxi-fare-guru-total-amount-prediction-challenge/test.csv


In [2]:
training_data = pd.read_csv("/kaggle/input/taxi-fare-guru-total-amount-prediction-challenge/train.csv")
training_data.head()

VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         1  2023-06-28 17:20:21   2023-06-28 16:34:45              1.0   
1         0  2023-06-29 23:05:01   2023-06-29 22:01:35              1.0   
2         1  2023-06-30 10:19:31   2023-06-30 11:13:10              1.0   
3         0  2023-06-29 13:23:09   2023-06-29 14:20:01              1.0   
4         1  2023-06-29 22:03:32   2023-06-29 22:22:22              3.0   

   trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0           2.14         1.0                  N           120             9   
1           2.70         1.0                  N            15           215   
2           1.15         1.0                  N           167           223   
3           0.40         1.0                  N           128           239   
4           1.10         1.0                  N           203            52   

  payment_type  extra  tip_amount  tolls_amount  improvement_surcharge  \
0  Credit Card    2.5    7.165589           0.0                    1.0   
1  Credit Card    3.5    6.067401           0.0                    1.0   
2  Credit Card    0.0    4.111547           0.0                    1.0   
3  Credit Card    2.5    6.411079           0.0                    1.0   
4  Credit Card    1.0    4.769377           0.0                    1.0   

   total_amount  congestion_surcharge  Airport_fee  
0         20.64                   2.5          0.0  
1         25.55                   2.5          0.0  
2         17.64                   2.5          0.0  
3         12.80                   2.5          0.0  
4         18.00                   2.5          0.0

In [3]:
training_data.shape

(175000, 17)

In [4]:
training_data.describe()

VendorID  passenger_count  trip_distance     RatecodeID  \
count  175000.000000    168923.000000  175000.000000  168923.000000   
mean        0.728377         1.357678       5.145930       1.518307   
std         0.445606         0.891283     394.971052       6.514678   
min         0.000000         0.000000       0.000000       1.000000   
25%         0.000000         1.000000       1.080000       1.000000   
50%         1.000000         1.000000       1.840000       1.000000   
75%         1.000000         1.000000       3.610000       1.000000   
max         2.000000         9.000000  135182.060000      99.000000   

        PULocationID   DOLocationID          extra     tip_amount  \
count  175000.000000  175000.000000  175000.000000  175000.000000   
mean      132.710349     132.701429       1.932143       6.127497   
std        76.148799      76.192493       1.948497       4.610834   
min         1.000000       1.000000      -7.500000       0.000079   
25%        67.000000      67.000000       0.000000       3.473321   
50%       133.000000     133.000000       1.000000       5.286217   
75%       199.000000     199.000000       2.500000       7.502746   
max       264.000000     264.000000      11.750000     484.876151   

        tolls_amount  improvement_surcharge   total_amount  \
count  175000.000000          175000.000000  175000.000000   
mean        0.646816               0.979689      29.633901   
std         2.328274               0.198775      25.425206   
min       -29.300000              -1.000000    -576.750000   
25%         0.000000               1.000000      16.300000   
50%         0.000000               1.000000      21.450000   
75%         0.000000               1.000000      31.800000   
max        80.000000               1.000000     587.250000   

       congestion_surcharge    Airport_fee  
count         168923.000000  168923.000000  
mean               2.246971       0.158825  
std                0.819216       0.511968  
min               -2.500000      -1.750000  
25%                2.500000       0.000000  
50%                2.500000       0.000000  
75%                2.500000       0.000000  
max                2.500000       1.750000

In [5]:
training_data.dtypes

VendorID                   int64
tpep_pickup_datetime      object
tpep_dropoff_datetime     object
passenger_count          float64
trip_distance            float64
RatecodeID               float64
store_and_fwd_flag        object
PULocationID               int64
DOLocationID               int64
payment_type              object
extra                    float64
tip_amount               float64
tolls_amount             float64
improvement_surcharge    float64
total_amount             float64
congestion_surcharge     float64
Airport_fee              float64
dtype: object

In [6]:
training_subset = training_data.select_dtypes(include = ['float', 'int'])

In [7]:
training_subset

VendorID  passenger_count  trip_distance  RatecodeID  PULocationID  \
0              1              1.0           2.14         1.0           120   
1              0              1.0           2.70         1.0            15   
2              1              1.0           1.15         1.0           167   
3              0              1.0           0.40         1.0           128   
4              1              3.0           1.10         1.0           203   
...          ...              ...            ...         ...           ...   
174995         1              3.0           3.45         1.0           147   
174996         1              1.0           9.44         1.0           154   
174997         0              1.0           2.40         1.0           168   
174998         1              1.0           4.71         1.0           240   
174999         1              1.0           1.01         1.0           153   

        DOLocationID  extra  tip_amount  tolls_amount  improvement_surcharge  \
0                  9    2.5    7.165589           0.0                    1.0   
1                215    3.5    6.067401           0.0                    1.0   
2                223    0.0    4.111547           0.0                    1.0   
3                239    2.5    6.411079           0.0                    1.0   
4                 52    1.0    4.769377           0.0                    1.0   
...              ...    ...         ...           ...                    ...   
174995           167    1.0    8.732495           0.0                    1.0   
174996           191    5.0    0.283275           0.0                    1.0   
174997           106    2.5    4.245354           0.0                    1.0   
174998           100    2.5   10.479776           0.0                    1.0   
174999            72    1.0    6.541699           0.0                    1.0   

        total_amount  congestion_surcharge  Airport_fee  
0              20.64                   2.5         0.00  
1              25.55                   2.5         0.00  
2              17.64                   2.5         0.00  
3              12.80                   2.5         0.00  
4              18.00                   2.5         0.00  
...              ...                   ...          ...  
174995         28.08                   2.5         0.00  
174996         59.95                   2.5         1.75  
174997         33.50                   2.5         0.00  
174998         40.80                   2.5         0.00  
174999         16.32                   2.5         0.00  

[175000 rows x 13 columns]

In [8]:
training_subset.isnull().sum()

VendorID                    0
passenger_count          6077
trip_distance               0
RatecodeID               6077
PULocationID                0
DOLocationID                0
extra                       0
tip_amount                  0
tolls_amount                0
improvement_surcharge       0
total_amount                0
congestion_surcharge     6077
Airport_fee              6077
dtype: int64

In [9]:
y = training_subset['total_amount']
X = training_subset.drop(columns = ["total_amount"])

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X,y, test_size = 0.2, random_state = 42)

In [11]:
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(missing_values=np.NaN,strategy='mean')
X_train = imp_mean.fit_transform(X_train)
X_val = imp_mean.fit_transform(X_val)

In [12]:
from sklearn.neighbors import KNeighborsRegressor
KNN = KNeighborsRegressor(n_neighbors=13)
KNN.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=13)

In [13]:
y_train = np.asarray(y_train)

In [14]:
y_val = np.asarray(y_val)
y_val

array([24.8 , 31.55, 24.84, ..., 24.  , 15.96, 17.1 ])

In [15]:
from sklearn.metrics import r2_score
predictions = KNN.predict(X_val)
r2_score(y_val, predictions)

0.7883423226406199

In [16]:
test_data = pd.read_csv("/kaggle/input/taxi-fare-guru-total-amount-prediction-challenge/test.csv")
test_data.head()

VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         1  2023-06-29 00:21:20   2023-06-29 00:25:20              1.0   
1         1  2023-06-30 17:44:43   2023-06-30 17:53:13              1.0   
2         1  2023-06-29 18:17:04   2023-06-29 19:23:48              1.0   
3         0  2023-06-30 21:33:53   2023-06-30 21:46:20              1.0   
4         1  2023-06-29 14:53:54   2023-06-29 15:22:17              1.0   

   trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0           4.95         1.0                  N            20             3   
1           2.10         1.0                  N             9            81   
2           0.95         1.0                  N            92            90   
3           0.80         1.0                  N            19           102   
4           4.01         1.0                  N           131           229   

  payment_type  extra  tip_amount  tolls_amount  improvement_surcharge  \
0  Credit Card    1.0    6.067612           0.0                    1.0   
1  Credit Card    2.5    6.191269           0.0                    1.0   
2         Cash    2.5    3.983872           0.0                    1.0   
3  Credit Card    3.5    6.839341           0.0                    1.0   
4         Cash    0.0    1.468943           0.0                    1.0   

   congestion_surcharge  Airport_fee  
0                   2.5          0.0  
1                   2.5          0.0  
2                   2.5          0.0  
3                   2.5          0.0  
4                   0.0          0.0

In [17]:
test_subset = test_data.select_dtypes(include = ['float', 'int'])

In [18]:
X_test = imp_mean.fit_transform(test_subset)
X_test

array([[1.  , 1.  , 4.95, ..., 1.  , 2.5 , 0.  ],
       [1.  , 1.  , 2.1 , ..., 1.  , 2.5 , 0.  ],
       [1.  , 1.  , 0.95, ..., 1.  , 2.5 , 0.  ],
       ...,
       [1.  , 1.  , 1.92, ..., 1.  , 2.5 , 0.  ],
       [0.  , 1.  , 5.4 , ..., 1.  , 2.5 , 0.  ],
       [1.  , 1.  , 1.31, ..., 1.  , 2.5 , 0.  ]])

In [19]:
predictions = KNN.predict(X_test)
predictions

array([25.32      , 22.3       , 18.42692308, ..., 19.53307692,
       27.31923077, 15.89846154])

In [20]:
sample = pd.read_csv("/kaggle/input/taxi-fare-guru-total-amount-prediction-challenge/sample.csv.csv")
sample.head()

ID  total_amount
0   1     24.456348
1   2     24.374058
2   3     19.878154
3   4     25.015569
4   5     22.252489

In [21]:
submission = pd.DataFrame(columns = ["ID", "total_amount"])
submission["ID"] = [i+1 for i in range(len(predictions))]
submission["total_amount"] = [x for x in predictions]

In [22]:
submission.head()

ID  total_amount
0   1     25.320000
1   2     22.300000
2   3     18.426923
3   4     19.198462
4   5     21.673077

In [23]:
submission.to_csv('submission.csv', index = False)